package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/lolay/triage/internal/engine"
)

// configDiscoveryNames mirrors internal/config discover order.
var configDiscoveryNames = []string{"triage.yaml", "triage.yml", ".triage.yaml", ".triage.yml"}

const initDefaultTarget = "triage.yaml"

func runInit(configArg string, stdout, stderr io.Writer, exitCode *int) error {
	cwd, err := os.Getwd()
	if err != nil {
		*exitCode = ExitUsageError
		_, _ = fmt.Fprintf(stderr, "triage: %v\n", err)
		return nil
	}

	target := initDefaultTarget
	if configArg != "" {
		target = configArg
	}

	targetPath := target
	if !filepath.IsAbs(targetPath) {
		targetPath = filepath.Join(cwd, target)
	}

	if err := checkInitTargetAvailable(configArg, cwd, targetPath, stderr, exitCode); err != nil {
		return err
	}
	if *exitCode != ExitOK {
		return nil
	}

	content := initTemplate(engine.CurrentPlatform())
	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		*exitCode = ExitUsageError
		_, _ = fmt.Fprintf(stderr, "triage: write %s: %v\n", target, err)
		return nil
	}

	_, _ = fmt.Fprintf(stdout, "triage: created %s\n", target)
	return nil
}

func checkInitTargetAvailable(configArg, cwd, targetPath string, stderr io.Writer, exitCode *int) error {
	if configArg == "" {
		for _, name := range configDiscoveryNames {
			p := filepath.Join(cwd, name)
			if _, err := os.Stat(p); err == nil {
				*exitCode = ExitUsageError
				_, _ = fmt.Fprintf(stderr, "triage: %s already exists\n", name)
				return nil
			}
		}
		return nil
	}

	info, err := os.Stat(targetPath)
	if err == nil {
		if info.IsDir() {
			*exitCode = ExitUsageError
			_, _ = fmt.Fprintf(stderr, "triage: %s is a directory\n", configArg)
			return nil
		}
		*exitCode = ExitUsageError
		_, _ = fmt.Fprintf(stderr, "triage: %s already exists\n", configArg)
		return nil
	}
	if !os.IsNotExist(err) {
		*exitCode = ExitUsageError
		_, _ = fmt.Fprintf(stderr, "triage: %v\n", err)
	}
	return nil
}

func initTemplate(platform string) string {
	if platform == "windows" {
		return initTemplateWindows
	}
	return initTemplatePOSIX
}

const initTemplatePOSIX = `# yaml-language-server: $schema=https://raw.githubusercontent.com/lolay/triage/main/schema/triage.schema.json
# triage.yaml — starter config generated by ` + "`triage --init`" + `
# Run ` + "`triage`" + ` to check your environment. See https://github.com/lolay/triage for docs.

default:
  - group: Core
    items:
      - tool: git
        hint: https://git-scm.com
      - tool: curl
  - group: Runtime
    items:
      - tool: node
        severity: warn
        hint: https://nodejs.org
      - tool: python3
        severity: warn
  - group: Environment
    items:
      - env: HOME
      - path: ~/.ssh
        severity: warn
`

const initTemplateWindows = `# yaml-language-server: $schema=https://raw.githubusercontent.com/lolay/triage/main/schema/triage.schema.json
# triage.yaml — starter config generated by ` + "`triage --init`" + `
# Run ` + "`triage`" + ` to check your environment. See https://github.com/lolay/triage for docs.

default:
  - group: Core
    items:
      - tool: git
        hint: https://git-scm.com
      - tool: pwsh
        hint: https://aka.ms/pscore6
  - group: Runtime
    items:
      - tool: node
        severity: warn
        hint: https://nodejs.org
      - tool: python
        severity: warn
  - group: Environment
    items:
      - env: USERPROFILE
      - env: APPDATA
`
